// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJKOiBnrK3KBFN3KQeRsZB76jDXNfj7Zg',
    appId: '1:864860318041:web:0d46460044cab420c7c448',
    messagingSenderId: '864860318041',
    projectId: 'noteapp-5d962',
    authDomain: 'noteapp-5d962.firebaseapp.com',
    storageBucket: 'noteapp-5d962.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsSn_d4i2QJhDkaGoxu3gi3XtaPjgmNGk',
    appId: '1:864860318041:android:1d6166e065959e3dc7c448',
    messagingSenderId: '864860318041',
    projectId: 'noteapp-5d962',
    storageBucket: 'noteapp-5d962.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi5bXDaX3I01VrGB0uSnB2i37xQpna5SE',
    appId: '1:864860318041:ios:9e9bc3dba9129553c7c448',
    messagingSenderId: '864860318041',
    projectId: 'noteapp-5d962',
    storageBucket: 'noteapp-5d962.appspot.com',
    iosBundleId: 'com.example.applicationDeNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi5bXDaX3I01VrGB0uSnB2i37xQpna5SE',
    appId: '1:864860318041:ios:9e9bc3dba9129553c7c448',
    messagingSenderId: '864860318041',
    projectId: 'noteapp-5d962',
    storageBucket: 'noteapp-5d962.appspot.com',
    iosBundleId: 'com.example.applicationDeNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJKOiBnrK3KBFN3KQeRsZB76jDXNfj7Zg',
    appId: '1:864860318041:web:a579fe67cb1350b2c7c448',
    messagingSenderId: '864860318041',
    projectId: 'noteapp-5d962',
    authDomain: 'noteapp-5d962.firebaseapp.com',
    storageBucket: 'noteapp-5d962.appspot.com',
  );

}